p = input('digite algo para saber seu tipo:')
print(p.isalpha())
print(p.islower())
print(p.isalnum())
print(p.isascii())
print(p.isdecimal())
print(p.isdigit())
print(p.isidentifier())
print(p.isnumeric())
print(p.isprintable())
print(p.isspace())
print(p.istitle())
print(p.isupper())
print (type(p))
